### ISSUE TITLE
List the dependencies of modules

### ISSUE THREAD

**Issue by luismfonseca** [ikaras/nodemcu-websocket-client#1]
Can you please add a list of dependencies to the README file?

It would be very useful as I want a different firmware than the one provided.

**Comment by ikaras** [comment]
Hi, thanks for interesting!
I've updated README and set [list of dependencies](https://github.com/ikaras/nodemcu-websocket-client#firmware-modules-dependencies).

Hope I didn't forgot anything.

**Comment by luismfonseca** [comment]
Thanks!
