### ISSUE TITLE
Sugesstion: Use lua compiled code

### ISSUE THREAD

**Issue by luismfonseca** [ikaras/nodemcu-websocket-client#2]
Running `node.compile` on the `.lua` files will make them use less RAM. This [command](http://nodemcu.readthedocs.org/en/dev/en/modules/node/#nodecompile) generates a `.lc` file with the same name.

It's harder to debug if there's an error as it doesn't tell you which line crashed, but the lesser RAM usage is probably worth it in this case.

You could write some checks to run `node.compile` if the `.lc` file doesn't exist.

**Comment by ikaras** [comment]
I'm noob in Lua (learning it only past 2 weeks after main work, also the same time I spent with nodemcu)
So, if you have a time, could you help to make all needed optimizations for repo? You could create pull request and I'll merge them.

What do think about it?

**Comment by luismfonseca** [comment]
I think you can close this issue, I did some quick tests with the latest dev firmware and I didn't find any difference in RAM among the two approaches.

In fact, my testing showed it was lower. The NodeMCU devs might have changed something...

**Comment by ikaras** [comment]
Ok, thanks.
